---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

<!-- #region -->
# How does violence impact mass mobilization?
* Quantitative
    * Protestor violence vs. length of protest
    * Protestor violence vs. outcome
* Qualitative
    * What comes first -- police brutality? or violence? Case study of Hong Kong: reports about police brutality?
    


What do protestors care about? 
* Protest length and protest counts and 
<!-- #endregion -->

## Next tasks:
    1. [DONE]Import the data into a dataframe 
    2. Figure out what kinds of graphs we should visualize. 
    
* Direct students to a limited collection of datasets
* Have them ask a question that the dataset could answer
* Answer the data quantitatively with the dataset
* Also do some minor qualitative research about the question to contextualize the quant answer


## Notes about the data set: 
Protest is defined as a gathering of 50 or more people to make a demand of the government
    
Clark, David; Regan, Patrick, 2016, "Mass Mobilization Protest Data", https://doi.org/10.7910/DVN/HTTWYL, Harvard Dataverse, V3, UNF:6:/IpCl1u0zpeC/hwamcT+Ng== [fileUNF]

Mass Mobilization around the World https://dataverse.harvard.edu/dataverse/MMdata
Ready made visualizations: https://massmobilization.shinyapps.io/Yearly_MM_Protests_and_Duration/

```{python}
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math
```

```{python}
df = pd.read_csv('mmALL_020619_v15.tab', sep='\t')
```

```{python}
df
```

```{python}
for col in df.columns: 
    print(col)
```

```{python}
x_var_label = "startyear"
y_var_label = "protesterviolence"
z_var_label = "region"
```

```{python}
df["participants_category"]
```

```{python}
from datetime import datetime
time_df = df[["startyear", "startmonth", "startday","endyear", "endmonth", "endday", "protesterviolence"]]
time_df = time_df.dropna()
length_array = []

for [startyear, startmonth, startday,endyear, endmonth, endday, protesterviolence] in time_df.values:
    start = datetime(int(startyear), int(startmonth), int(startday))
    end  = datetime(int(endyear), int(endmonth), int(endday))             
    duration = end - start                     
    days  = duration.days  + 1 # if a protest starts and ends on the same day, we consider that one day of protest.
    length_array.append([days, protesterviolence])
```

```{python}
length_array
```

```{python}
df_three_col = df[[x_var_label, y_var_label, z_var_label]]  # creating new dataframe with 2 columns
df_three_col = df_three_col.dropna() # removing rows with no response (NaN)
years_list = [x for [x,y,z] in df_three_col.values]  # copying data from dataframe to list
violent_years_list = [x for [x,y,z] in df_three_col.values if y > 0]  # copying data from dataframe to list
asian_years_list = [x for [x,y,z] in df_three_col.values if z == 5]  # copying data from dataframe to list
violent_asian_years_list = [x for [x,y,z] in df_three_col.values if z == 5 and y > 0]
```

```{python}
years_dict = {
}

for year in years_list:
    if year in years_dict:
        years_dict[year] = years_dict[year] + 1
    else:
        years_dict[year] = 1
```

```{python}
violent_years_dict = {
}

for year in violent_years_list:
    if year in violent_years_dict:
        violent_years_dict[year] = violent_years_dict[year] + 1
    else:
        violent_years_dict[year] = 1
```

```{python}
asian_years_dict = {
}

for year in asian_years_list:
    if year in asian_years_dict:
        asian_years_dict[year] = asian_years_dict[year] + 1
    else:
        asian_years_dict[year] = 1
```

```{python}
violent_asian_years_dict = {
}

for year in violent_asian_years_list:
    if year in violent_asian_years_dict:
        violent_asian_years_dict[year] = violent_asian_years_dict[year] + 1
    else:
        violent_asian_years_dict[year] = 1
```

```{python}
plt.scatter(years_dict.keys(), years_dict.values(),c='green',alpha=0.5, label="Total Protests")
plt.scatter(violent_years_dict.keys(), violent_years_dict.values(),c='red',alpha=0.5, label="Violent Protests")
plt.xlabel('Year')
plt.ylabel('Number of Protests')
plt.legend()
```

```{python}
plt.scatter(asian_years_dict.keys(), asian_years_dict.values(),c='blue',alpha=0.5, label="Total Protests in Asia")
plt.scatter(violent_asian_years_dict.keys(), violent_asian_years_dict.values(),c='red',alpha=0.5, label="Total Protests in Asia")
plt.xlabel('Year')
plt.ylabel('Number of Protests')
plt.legend()
```

```{python}
non_violent_lengths = [i[0] for i in length_array if i[1] < 1 and i[0] > 1 and i[0] < 600]
violent_lengths = [i[0] for i in length_array if i[1] > 0 and i[0] > 1 and i[0] < 600]

figure, axes = plt.subplots()
axes.boxplot(non_violent_lengths, vert=False)
plt.xlabel('Non-violent protest lengths')
```

```{python}
figure, axes = plt.subplots()
axes.boxplot(violent_lengths, vert=False)
plt.xlabel('Violent protest lengths')
```

```{python}
# STUDENT WORK
def calculate_mean(list_of_numbers):
    """
    Returns the average (mean) of a list of numbers.
    input: list of ints (or floats)
    output: float
    """
    return sum (list_of_numbers)/len(list_of_numbers)

# STUDENT WORK
def is_even(number):
    """
    Returns True if the number is even. Otherwise, False.
    This is useful because the rule for calculating the median is different 
    when there are an even number of elements in the list.
    """
    return number % 2 == 0

def sort_list(unsorted_list):
    """
    Sorts the list of values and returns a list in ascending order (from lowest to highest)
    input: list of ints(or floats)
    output: list of ints(or floats)
    """
    return sorted(unsorted_list)


def calculate_median(sorted_list):
    """
    Takes the sorted list, returns the median of the list
    input: list of ints(or floats)
    output: integer (or float)
    """
    if is_even(len(sorted_list)):
        middle_pos = int(len(sorted_list) / 2)
        median = (sorted_list[middle_pos - 1] + sorted_list[middle_pos]) / 2.0
    else:
        middle_pos = int((len(sorted_list) / 2) + 0.5)
        median = sorted_list[middle_pos - 1]
    return median
```

```{python}
calculate_mean(violent_lengths)
```

```{python}
calculate_mean(non_violent_lengths)
```

```{python}

```
